### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by LK4D4** [sdboyer/gps#156]
Encountered in dep
```
fatal error: concurrent map writes

goroutine 1 [running]:
runtime.throw(0x8109ce, 0x15)
        /home/moroz/go/src/runtime/panic.go:566 +0x95 fp=0xc420570aa8 sp=0xc420570a88
runtime.mapassign1(0x7a0c80, 0xc420808390, 0xc420570c80, 0xc420570c70)
        /home/moroz/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc420570b90 sp=0xc420570aa8
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*gitSource).listVersions(0xc420075680, 0xc420261720, 0x1e, 0x0, 0x0, 0x9bade0)
        /home/moroz/project/workspace/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/vcs_source.go:126 +0x48f fp=0xc420570d28 sp=0xc420570b90
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*SourceMgr).ListVersions(0xc42008e300, 0xc420261720, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/moroz/project/workspace/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/source_manager.go:395 +0x1f6 fp=0xc420570d80 sp=0xc420570d28
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*bridge).ListVersions(0xc4205a9640, 0xc420261720, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9ba720)
        /home/moroz/project/workspace/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/bridge.go:94 +0x138 fp=0xc420570e60 sp=0xc420570d80
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*solver).unselectedComparator(0xc42010a870, 0x13, 0x9, 0x50)
        /home/moroz/project/workspace/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/solver.go:991 +0x30a fp=0xc420571028 sp=0xc420570e60
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*solver).(github.com/golang/dep/vendor/github.com/sdboyer/gps.unselectedComparator)-fm(0x13, 0x9, 0xc4201ba0f0)
        /home/moroz/project/workspace/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/solver.go:276 +0x3e fp=0xc420571058 sp=0xc420571028
github.com/golang/dep/vendor/github.com/sdboyer/gps.unselected.Less(0xc420320a00, 0x14, 0x20, 0xc4203acb50, 0x13, 0x9, 0x0)
        /home/moroz/project/workspace/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/selection.go:160 +0x3a fp=0xc420571080 sp=0xc420571058
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*unselected).Less(0xc4201bf980, 0x13, 0x9, 0x0)
        <autogenerated>:84 +0x81 fp=0xc4205710c8 sp=0xc420571080
container/heap.up(0x9b9940, 0xc4201bf980, 0x13)
        /home/moroz/go/src/container/heap/heap.go:93 +0x64 fp=0xc420571100 sp=0xc4205710c8
container/heap.Push(0x9b9940, 0xc4201bf980, 0x7d6e40, 0xc4201ba0f0)
        /home/moroz/go/src/container/heap/heap.go:54 +0x7e fp=0xc420571128 sp=0xc420571100
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*solver).selectRoot(0xc42010a870, 0xc4208176b0, 0xc420817860)
        /home/moroz/project/workspace/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/solver.go:479 +0x718 fp=0xc4205716c0 sp=0xc420571128
github.com/golang/dep/vendor/github.com/sdboyer/gps.(*solver).Solve(0xc42010a870, 0x3c, 0xc42001c066, 0x1a, 0xc420143050)
        /home/moroz/project/workspace/src/github.com/golang/dep/vendor/github.com/sdboyer/gps/solver.go:312 +0x6a fp=0xc4205718d8 sp=0xc4205716c0
main.(*initCommand).Run(0x9f4188, 0xc42000c2c0, 0x0, 0x0, 0x0, 0x0)
        /home/moroz/project/workspace/src/github.com/golang/dep/init.go:153 +0x102f fp=0xc420571db0 sp=0xc4205718d8
main.main()
        /home/moroz/project/workspace/src/github.com/golang/dep/main.go:99 +0x68b fp=0xc420571f38 sp=0xc420571db0
runtime.main()
        /home/moroz/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420571f90 sp=0xc420571f38
runtime.goexit()
        /home/moroz/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420571f98 sp=0xc420571f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/moroz/go/src/runtime/asm_amd64.s:2086 +0x1
```

**Comment by sdboyer** [comment]
Yeah, @freeformz ran into this a couple weeks ago - https://github.com/golang/dep/pull/87#issuecomment-271458682. Total derp on my part. I'm working on some race conditions in #136, though those are sorta separate and I suspect I'm going to have to defer this one.

I may hack this particular problem into submission with some more mutex trickery, but I need to do a generalized refactor of how the source manager works. It needs to move to a channel-based system that can serialize and fold together calls to the underlying source (vcs) handlers, and their caches.

In any case, thanks for reporting this. It's definitely on my radar, fix isn't too bad, and I should hopefully have it soon.
