### ISSUE TITLE
`TestMonitoredCmd` is flaky

### ISSUE THREAD

**Issue by spenczar** [sdboyer/gps#183]
On a fresh copy of `gps`, I ran `glide install`, then `go test -v .`, and got this:

```
=== RUN   TestMonitoredCmd
--- FAIL: TestMonitoredCmd (0.37s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10833e8]

goroutine 49 [running]:
testing.tRunner.func1(0xc4203e41a0)
	/Users/snelson/go1.8/src/testing/testing.go:622 +0x29d
panic(0x14a87a0, 0x1a77730)
	/Users/snelson/go1.8/src/runtime/panic.go:489 +0x2cf
os.(*Process).signal(0x0, 0x1a506c0, 0x1a4a370, 0x0, 0x0)
	/Users/snelson/go1.8/src/os/exec_unix.go:56 +0x38
os.(*Process).Signal(0x0, 0x1a506c0, 0x1a4a370, 0x58c2bccc, 0x2a6d631b)
	/Users/snelson/go1.8/src/os/exec.go:121 +0x3f
os.(*Process).kill(0x0, 0x2a6d631b, 0x1a82420)
	/Users/snelson/go1.8/src/os/exec_posix.go:53 +0x43
os.(*Process).Kill(0x0, 0xc4203ce901, 0xc420043d78)
	/Users/snelson/go1.8/src/os/exec.go:106 +0x2b
github.com/sdboyer/gps.(*monitoredCmd).run(0xc4203c7d80, 0x0, 0x0)
	/Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:41 +0x1a3
github.com/sdboyer/gps.TestMonitoredCmd(0xc4203e41a0)
	/Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:26 +0x176
testing.tRunner(0xc4203e41a0, 0x153efd0)
	/Users/snelson/go1.8/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/Users/snelson/go1.8/src/testing/testing.go:697 +0x2ca
exit status 2
```
A second run of `go test -v .` did not panic, so I assume this is some tricky race.

**Comment by spenczar** [comment]
Yep, looks like a data race, from `go test -race`:
```
=== RUN   TestMonitoredCmd
==================
WARNING: DATA RACE
Read at 0x00c42000c2a8 by goroutine 49:
  github.com/sdboyer/gps.(*monitoredCmd).hasTimedOut()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:56 +0x15a
  github.com/sdboyer/gps.(*monitoredCmd).run()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:40 +0x1b8
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:37 +0x4f1
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107

Previous write at 0x00c42000c2a8 by goroutine 55:
  github.com/sdboyer/gps.(*activityBuffer).Write()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:81 +0x69
  io.copyBuffer()
      /Users/snelson/go1.8/src/io/io.go:392 +0x27d
  io.Copy()
      /Users/snelson/go1.8/src/io/io.go:360 +0x7e
  os/exec.(*Cmd).writerDescriptor.func1()
      /Users/snelson/go1.8/src/os/exec/exec.go:254 +0x68
  os/exec.(*Cmd).Start.func1()
      /Users/snelson/go1.8/src/os/exec/exec.go:371 +0x38

Goroutine 49 (running) created at:
  testing.(*T).Run()
      /Users/snelson/go1.8/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /Users/snelson/go1.8/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
  testing.runTests()
      /Users/snelson/go1.8/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /Users/snelson/go1.8/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/sdboyer/gps/_test/_testmain.go:154 +0x20f

Goroutine 55 (running) created at:
  os/exec.(*Cmd).Start()
      /Users/snelson/go1.8/src/os/exec/exec.go:372 +0x924
  os/exec.(*Cmd).Run()
      /Users/snelson/go1.8/src/os/exec/exec.go:277 +0x3c
  github.com/sdboyer/gps.(*monitoredCmd).run.func1()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x50
==================
==================
WARNING: DATA RACE
Read at 0x00c4204320a0 by goroutine 49:
  github.com/sdboyer/gps.(*monitoredCmd).run()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:41 +0x1f5
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:37 +0x4f1
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107

Previous write at 0x00c4204320a0 by goroutine 54:
  os/exec.(*Cmd).Start()
      /Users/snelson/go1.8/src/os/exec/exec.go:354 +0x78c
  os/exec.(*Cmd).Run()
      /Users/snelson/go1.8/src/os/exec/exec.go:277 +0x3c
  github.com/sdboyer/gps.(*monitoredCmd).run.func1()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x50

Goroutine 49 (running) created at:
  testing.(*T).Run()
      /Users/snelson/go1.8/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /Users/snelson/go1.8/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
  testing.runTests()
      /Users/snelson/go1.8/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /Users/snelson/go1.8/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/sdboyer/gps/_test/_testmain.go:154 +0x20f

Goroutine 54 (running) created at:
  github.com/sdboyer/gps.(*monitoredCmd).run()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x10f
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:37 +0x4f1
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
==================
==================
WARNING: DATA RACE
Read at 0x00c420442150 by goroutine 49:
  os.(*Process).signal()
      /Users/snelson/go1.8/src/os/exec_unix.go:56 +0x51
  os.(*Process).Signal()
      /Users/snelson/go1.8/src/os/exec.go:121 +0x4c
  os.(*Process).kill()
      /Users/snelson/go1.8/src/os/exec_posix.go:53 +0x64
  os.(*Process).Kill()
      /Users/snelson/go1.8/src/os/exec.go:106 +0x38
  github.com/sdboyer/gps.(*monitoredCmd).run()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:41 +0x210
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:37 +0x4f1
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107

Previous write at 0x00c420442150 by goroutine 54:
  os.newProcess()
      /Users/snelson/go1.8/src/os/exec.go:24 +0x5d
  os.startProcess()
      /Users/snelson/go1.8/src/os/exec_posix.go:49 +0x52c
  os.StartProcess()
      /Users/snelson/go1.8/src/os/exec.go:94 +0x7a
  os/exec.(*Cmd).Start()
      /Users/snelson/go1.8/src/os/exec/exec.go:359 +0x751
  os/exec.(*Cmd).Run()
      /Users/snelson/go1.8/src/os/exec/exec.go:277 +0x3c
  github.com/sdboyer/gps.(*monitoredCmd).run.func1()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x50

Goroutine 49 (running) created at:
  testing.(*T).Run()
      /Users/snelson/go1.8/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /Users/snelson/go1.8/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
  testing.runTests()
      /Users/snelson/go1.8/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /Users/snelson/go1.8/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/sdboyer/gps/_test/_testmain.go:154 +0x20f

Goroutine 54 (running) created at:
  github.com/sdboyer/gps.(*monitoredCmd).run()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x10f
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:37 +0x4f1
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
==================
==================
WARNING: DATA RACE
Read at 0x00c420442160 by goroutine 49:
  sync/atomic.LoadInt32()
      /Users/snelson/go1.8/src/runtime/race_amd64.s:206 +0xb
  os.(*Process).done()
      /Users/snelson/go1.8/src/os/exec.go:34 +0x3e
  os.(*Process).signal()
      /Users/snelson/go1.8/src/os/exec_unix.go:64 +0x1dc
  os.(*Process).Signal()
      /Users/snelson/go1.8/src/os/exec.go:121 +0x4c
  os.(*Process).kill()
      /Users/snelson/go1.8/src/os/exec_posix.go:53 +0x64
  os.(*Process).Kill()
      /Users/snelson/go1.8/src/os/exec.go:106 +0x38
  github.com/sdboyer/gps.(*monitoredCmd).run()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:41 +0x210
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:37 +0x4f1
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107

Previous write at 0x00c420442160 by goroutine 54:
  os.newProcess()
      /Users/snelson/go1.8/src/os/exec.go:24 +0x5d
  os.startProcess()
      /Users/snelson/go1.8/src/os/exec_posix.go:49 +0x52c
  os.StartProcess()
      /Users/snelson/go1.8/src/os/exec.go:94 +0x7a
  os/exec.(*Cmd).Start()
      /Users/snelson/go1.8/src/os/exec/exec.go:359 +0x751
  os/exec.(*Cmd).Run()
      /Users/snelson/go1.8/src/os/exec/exec.go:277 +0x3c
  github.com/sdboyer/gps.(*monitoredCmd).run.func1()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x50

Goroutine 49 (running) created at:
  testing.(*T).Run()
      /Users/snelson/go1.8/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /Users/snelson/go1.8/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
  testing.runTests()
      /Users/snelson/go1.8/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /Users/snelson/go1.8/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/sdboyer/gps/_test/_testmain.go:154 +0x20f

Goroutine 54 (running) created at:
  github.com/sdboyer/gps.(*monitoredCmd).run()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x10f
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:37 +0x4f1
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
==================
==================
WARNING: DATA RACE
Read at 0x00c42005e088 by goroutine 49:
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:48 +0x854
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107

Previous write at 0x00c42005e088 by goroutine 55:
  bytes.(*Buffer).grow()
      /Users/snelson/go1.8/src/bytes/buffer.go:113 +0x362
  bytes.(*Buffer).Write()
      /Users/snelson/go1.8/src/bytes/buffer.go:137 +0x60
  github.com/sdboyer/gps.(*activityBuffer).Write()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:82 +0xdd
  io.copyBuffer()
      /Users/snelson/go1.8/src/io/io.go:392 +0x27d
  io.Copy()
      /Users/snelson/go1.8/src/io/io.go:360 +0x7e
  os/exec.(*Cmd).writerDescriptor.func1()
      /Users/snelson/go1.8/src/os/exec/exec.go:254 +0x68
  os/exec.(*Cmd).Start.func1()
      /Users/snelson/go1.8/src/os/exec/exec.go:371 +0x38

Goroutine 49 (running) created at:
  testing.(*T).Run()
      /Users/snelson/go1.8/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /Users/snelson/go1.8/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
  testing.runTests()
      /Users/snelson/go1.8/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /Users/snelson/go1.8/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/sdboyer/gps/_test/_testmain.go:154 +0x20f

Goroutine 55 (running) created at:
  os/exec.(*Cmd).Start()
      /Users/snelson/go1.8/src/os/exec/exec.go:372 +0x924
  os/exec.(*Cmd).Run()
      /Users/snelson/go1.8/src/os/exec/exec.go:277 +0x3c
  github.com/sdboyer/gps.(*monitoredCmd).run.func1()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x50
==================
==================
WARNING: DATA RACE
Read at 0x00c42005e070 by goroutine 49:
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:48 +0x871
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107

Previous write at 0x00c42005e070 by goroutine 55:
  bytes.(*Buffer).grow()
      /Users/snelson/go1.8/src/bytes/buffer.go:112 +0x325
  bytes.(*Buffer).Write()
      /Users/snelson/go1.8/src/bytes/buffer.go:137 +0x60
  github.com/sdboyer/gps.(*activityBuffer).Write()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:82 +0xdd
  io.copyBuffer()
      /Users/snelson/go1.8/src/io/io.go:392 +0x27d
  io.Copy()
      /Users/snelson/go1.8/src/io/io.go:360 +0x7e
  os/exec.(*Cmd).writerDescriptor.func1()
      /Users/snelson/go1.8/src/os/exec/exec.go:254 +0x68
  os/exec.(*Cmd).Start.func1()
      /Users/snelson/go1.8/src/os/exec/exec.go:371 +0x38

Goroutine 49 (running) created at:
  testing.(*T).Run()
      /Users/snelson/go1.8/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /Users/snelson/go1.8/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
  testing.runTests()
      /Users/snelson/go1.8/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /Users/snelson/go1.8/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/sdboyer/gps/_test/_testmain.go:154 +0x20f

Goroutine 55 (running) created at:
  os/exec.(*Cmd).Start()
      /Users/snelson/go1.8/src/os/exec/exec.go:372 +0x924
  os/exec.(*Cmd).Run()
      /Users/snelson/go1.8/src/os/exec/exec.go:277 +0x3c
  github.com/sdboyer/gps.(*monitoredCmd).run.func1()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x50
==================
==================
WARNING: DATA RACE
Read at 0x00c42005e090 by goroutine 49:
  runtime.slicebytetostring()
      /Users/snelson/go1.8/src/runtime/string.go:72 +0x0
  github.com/sdboyer/gps.TestMonitoredCmd()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd_test.go:48 +0x8c3
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107

Previous write at 0x00c42005e090 by goroutine 55:
  runtime.slicecopy()
      /Users/snelson/go1.8/src/runtime/slice.go:160 +0x0
  bytes.(*Buffer).Write()
      /Users/snelson/go1.8/src/bytes/buffer.go:138 +0xeb
  github.com/sdboyer/gps.(*activityBuffer).Write()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:82 +0xdd
  io.copyBuffer()
      /Users/snelson/go1.8/src/io/io.go:392 +0x27d
  io.Copy()
      /Users/snelson/go1.8/src/io/io.go:360 +0x7e
  os/exec.(*Cmd).writerDescriptor.func1()
      /Users/snelson/go1.8/src/os/exec/exec.go:254 +0x68
  os/exec.(*Cmd).Start.func1()
      /Users/snelson/go1.8/src/os/exec/exec.go:371 +0x38

Goroutine 49 (running) created at:
  testing.(*T).Run()
      /Users/snelson/go1.8/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /Users/snelson/go1.8/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /Users/snelson/go1.8/src/testing/testing.go:657 +0x107
  testing.runTests()
      /Users/snelson/go1.8/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /Users/snelson/go1.8/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/sdboyer/gps/_test/_testmain.go:154 +0x20f

Goroutine 55 (running) created at:
  os/exec.(*Cmd).Start()
      /Users/snelson/go1.8/src/os/exec/exec.go:372 +0x924
  os/exec.(*Cmd).Run()
      /Users/snelson/go1.8/src/os/exec/exec.go:277 +0x3c
  github.com/sdboyer/gps.(*monitoredCmd).run.func1()
      /Users/snelson/go/src/github.com/sdboyer/gps/cmd.go:35 +0x50
==================
--- FAIL: TestMonitoredCmd (0.89s)
	testing.go:610: race detected during execution of test
```

**Comment by sdboyer** [comment]
derp derp - good catch, thank you!
